import { Category } from "../models/category";

export const categoryValue: Category[] = [
    {
        _id: "1",
        name: 'Shampoo',
        description: 'Limpiador para el cabello.',
        category_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "2",
        name: 'Acondicionador',
        description: 'Producto para suavizar y desenredar el cabello.',
        category_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "3",
        name: 'Tijeras',
        description: 'Herramienta de corte para estilistas.',
        category_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "4",
        name: 'Secador de pelo',
        description: 'Dispositivo para secar el cabello.',
        category_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "5",
        name: 'Tinte de pelo',
        description: 'Producto para cambiar el color del cabello.',
        category_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "6",
        name: 'Cepillos',
        description: 'Herramientas para peinar el cabello.',
        category_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "7",
        name: 'Capas de corte',
        description: 'Vestimenta para proteger la ropa durante el corte del cabello.',
        category_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "8",
        name: 'Planchas',
        description: 'Dispositivo para alisar el cabello.',
        category_id: 8,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "9",
        name: 'Mascarillas capilares',
        description: 'Tratamiento para nutrir y mejorar la salud del cabello.',
        category_id: 9,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "10",
        name: 'Extensiones de cabello',
        description: 'Cabello artificial o natural agregado para aumentar la longitud o volumen.',
        category_id: 10,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "11",
        name: 'Maquinillas de afeitar',
        description: 'Herramienta para cortar el cabello de manera precisa.',
        category_id: 11,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "12",
        name: 'Peines',
        description: 'Herramienta para desenredar y peinar el cabello.',
        category_id: 12,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "15",
        name: 'Manicura',
        description: 'Cuidado y embellecimiento de las uñas.',
        category_id: 13,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "16",
        name: 'Tratamientos capilares',
        description: 'Productos para mejorar la salud general del cabello.',
        category_id: 14,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "17",
        name: 'Herramientas de estilista',
        description: 'Instrumentos utilizados por los estilistas para cortar y peinar el cabello.',
        category_id: 15,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "18",
        name: 'Productos de peinado',
        description: 'Productos para estilizar y dar forma al cabello.',
        category_id: 16,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "19",
        name: 'Productos para la barba',
        description: 'Productos específicos para el cuidado de la barba.',
        category_id: 17,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "20",
        name: 'Accesorios para el cabello',
        description: 'Artículos decorativos o funcionales para el cabello.',
        category_id: 18,
        created_at: new Date(),
        updated_at: new Date(),
    },
]

export const categoryService: Category[] = [
    {
        _id: "1",
        name: 'Corte de pelo',
        description: '',
        category_id: 1,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "2",
        name: 'Facial',
        description: '',
        category_id: 2,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "3",
        name: 'Manicure',
        description: '',
        category_id: 3,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "4",
        name: 'Tratamiento capilar',
        description: '',
        category_id: 4,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "5",
        name: 'Bienestar',
        description: '',
        category_id: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "6",
        name: 'Maquillaje',
        description: '',
        category_id: 6,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: "7",
        name: 'Peinados',
        description: '',
        category_id: 7,
        created_at: new Date(),
        updated_at: new Date(),
    },
]