import { Product } from "../models/product";

enum Category {
    Shampoo = 1, // Shampoo
    Conditioner = 2, // Acondicionador
    Scissors = 3, // Tijeras
    HairDryer = 4, // Secador de pelo
    HairDye = 5, // Tinte de pelo 
    Brushes = 6, // Cepillos
    CuttingCapes = 7, // Capas de corte
    FlatIrons = 8, // Planchas
    HairMasks = 9, // Mascarillas capilares
    HairExtensions = 10, // Extensiones de cabello
    Razors = 11, // Maquinillas de afeitar
    Combs = 12, // Peines
    Manicure = 15, // Manicura
    HairTreatment = 16, // Tratamientos capilares
    StylistTools = 17, // Herramientas de estilista
    StylingProducts = 18, // Productos de peinado
    BeardProducts = 19, // Productos para la barba
    HairAccessories = 20, // Accesorios para el cabello
}
export const productsValue: Product[] = [
    {
        _id: '1',
        name: 'Moroccanoil Moisture Repair Shampoo 250ml',
        price: 110,
        description: 'Shampoo reparador con aceite de argán para cabello dañado.',
        category: Category.Shampoo,
        stock: 0,
        quantity: 0,
        imageUrl: '../../assets/image/products/SHAMPOO-REPAIR-1.png',
        barcode: '123456789012',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Restaura la hidratación', 'Deja el cabello suave'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '2',
        name: 'Aussie, acondicionador húmedo milagroso de 3 minutos, 8 onzas',
        price: 45,
        description: 'Acondicionador hidratante para un cabello suave en solo 3 minutos.',
        category: Category.Conditioner,
        stock: 30,
        quantity: 0,
        imageUrl: '../../assets/image/products/aussie.jpg',
        barcode: '987654321098',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Hidratación intensiva', 'Mejora la textura'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '3',
        name: 'Tijeras profesionales para corte de pelo Hikari',
        price: 70,
        description: 'Tijeras de corte profesional para estilistas y peluqueros.',
        category: Category.Scissors,
        stock: 15,
        quantity: 0,
        imageUrl: '../../assets/image/products/hikari.jpg',
        barcode: '1357924680',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Afiladas y precisas', 'Excelente durabilidad'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '4',
        name: 'Dyson Supersonic Hair Dryer',
        price: 300,
        description: 'Secador de pelo con tecnología avanzada para un secado rápido y controlado.',
        category: Category.HairDryer,
        stock: 0,
        quantity: 0,
        imageUrl: '../../assets/image/products/dyson.jpg',
        barcode: '2468013579',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Secado rápido', 'Diseño ergonómico'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '5',
        name: "L'Oréal Paris Tinte Excellence Sin Amoniaco 5U Castaño Claro Universal",
        price: 34,
        description: 'Tinte para cabello permanente con una fórmula rica y duradera.',
        category: Category.HairDye,
        stock: 7,
        quantity: 0,
        imageUrl: '../../assets/image/products/loreal-tinte.jpg',
        barcode: '9870123456',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Colores vibrantes', 'Fácil de aplicar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '6',
        name: 'Redken Tratamiento All Soft Mega Curls para cabello con rulos 150 ml',
        price: 131,
        description: 'Tratamiento sin enjuague para hidratar y suavizar el cabello.',
        category: Category.HairTreatment,
        stock: 6,
        quantity: 0,
        imageUrl: '../../assets/image/products/redken.jpg',
        barcode: '112233445566',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Hidratación profunda', 'Deja el cabello manejable'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '7',
        name: 'Plancha para Cabello Gama Elegance 3D',
        price: 80,
        description: 'Plancha ultra delgada para alisar el cabello con tecnología de titanio.',
        category: Category.FlatIrons,
        stock: 5,
        quantity: 0,
        imageUrl: '../../assets/image/products/plancha.jpg',
        barcode: '998877665544',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Alisado suave', 'Calentamiento rápido'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '8',
        name: 'Moroccanoil Máscara Capilar Reconstituyente 250 ML',
        price: 75,
        description: 'Mascarilla capilar restauradora para cabellos debilitados.',
        category: Category.HairMasks,
        stock: 6,
        quantity: 0,
        imageUrl: '../../assets/image/products/moroccanoil.jpg',
        barcode: '554433221199',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Reparación intensiva', 'Suaviza el cabello'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '9',
        name: 'Extensiones de cabello 100% humano',
        price: 55,
        description: 'Extensiones de cabello humano para agregar longitud y volumen.',
        category: Category.HairExtensions,
        stock: 11,
        quantity: 0,
        imageUrl: '../../assets/image/products/extension.jpg',
        barcode: '765432109876',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Aspecto natural', 'Fácil de colocar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '10',
        name: 'Maquinilla de afeitar Utopia Care Professional Barber',
        price: 60,
        description: 'Navaja de estilismo con hoja de plumas para cortes precisos.',
        category: Category.Razors,
        stock: 8,
        quantity: 0,
        imageUrl: '../../assets/image/products/rasuradora.jpg',
        barcode: '321098765432',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Cortes suaves', 'Manejo fácil'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '11',
        name: 'Juego de peines de fibra de carbono',
        price: 30,
        description: 'Peine profesional para desenredar y dar forma al cabello.',
        category: Category.Combs,
        stock: 4,
        quantity: 0,
        imageUrl: '../../assets/image/products/combo-peines.jpg',
        barcode: '456789012345',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Diseño ergonómico', 'Antiestático'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '12',
        name: 'OPI Me Myself – Pack minis Nail Lacquers',
        price: 69,
        description: 'Set de esmaltes de uñas de alta calidad para manicura profesional.',
        category: Category.Manicure,
        stock: 5,
        quantity: 0,
        imageUrl: '../../assets/image/products/opi-me.jpg',
        barcode: '987654321011',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Colores vibrantes', 'Larga duración'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '13',
        name: 'Living Proof Perfect Hair Shampoo Seco De Día  198 ml 4 oz',
        price: 132,
        description: 'Champú en seco para limpiar y refrescar el cabello sin agua.',
        category: Category.StylingProducts,
        stock: 4,
        quantity: 0,
        imageUrl: '../../assets/image/products/living.jpg',
        barcode: '223344556677',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Refresca instantáneamente', 'No deja residuos'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '14',
        name: 'Pomada para el cabello para hombre de American Crew 3 oz',
        price: 18.50,
        description: 'Crema moldeadora para estilos texturizados y definidos.',
        category: Category.StylingProducts,
        stock: 9,
        quantity: 0,
        imageUrl: '../../assets/image/products/pomada.jpg',
        barcode: '889900112233',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Fijación fuerte', 'Acabado natural'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '15',
        name: 'Billy Jealousy Kit de envidia de barba',
        price: 33,
        description: 'Kit completo para el cuidado y estilo de la barba.',
        category: Category.BeardProducts,
        stock: 15,
        quantity: 0,
        imageUrl: '../../assets/image/products/billy.jpg',
        barcode: '112233445566',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Suaviza la barba', 'Aroma agradable'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '16',
        name: 'Scunci Gancho 1Pk Open Cut Claw Clip',
        price: 10,
        description: 'Pinzas para el cabello con agarre antideslizante.',
        category: Category.HairAccessories,
        stock: 15,
        quantity: 0,
        imageUrl: '../../assets/image/products/scunci.jpg',
        barcode: '998877665544',
        onSale: true,
        unitsPerPackage: 3,
        reviews: ['Sujeción firme', 'Ideal para peinados'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '17',
        name: 'Revlon One-Step Secador Y Voluminizador Salon',
        price: 70,
        description: 'Secador y voluminizador en un solo paso para un peinado rápido.',
        category: Category.HairDryer,
        stock: 7,
        quantity: 0,
        imageUrl: '../../assets/image/products/revlon.jpg',
        barcode: '223344556677',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Secado rápido', 'Aumenta el volumen'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '18',
        name: 'Babyliss Pro Barberology Clipper',
        price: 75,
        description: 'Cortadora de cabello profesional para cortes precisos.',
        category: Category.StylistTools,
        stock: 5,
        quantity: 0,
        imageUrl: '../../assets/image/products/babyliss.jpg',
        barcode: '889900112233',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Cortes uniformes', 'Cuchillas afiladas'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '19',
        name: 'Kérastase Resistance Bain Force Architecte Shampoo 250ml',
        price: 112,
        description: 'Shampoo reconstructivo para fortalecer y reconstruir el cabello.',
        category: Category.Shampoo,
        stock: 2,
        quantity: 0,
        imageUrl: '../../assets/image/products/kerastase.jpg',
        barcode: '112233445566',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Fortalece el cabello', 'Revitaliza la fibra capilar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '20',
        name: 'Olaplex No. 7 Bonding Oil 30ml (Aceite Capilar)',
        price: 28,
        description: 'Aceite reparador para fortalecer, suavizar y dar brillo al cabello.',
        category: Category.HairTreatment,
        stock: 4,
        quantity: 0,
        imageUrl: '../../assets/image/products/acite-capilar.jpg',
        barcode: '998877665544',
        onSale: true,
        unitsPerPackage: 1,
        reviews: ['Restauración profunda', 'Textura no grasa'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '21',
        name: "Tinte Capilar Permanente EXCELLENCE Sin Amoníaco 4U Castaño Caja 1un",
        price: 34,
        description: 'Tinte para cabello permanente con una fórmula rica y duradera.',
        category: Category.HairDye,
        stock: 10,
        quantity: 0,
        imageUrl: '../../assets/image/products/tinte-2.jpg',
        barcode: '9870123456',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Colores vibrantes', 'Fácil de aplicar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '22',
        name: "Tinte Capilar Permanente EXCELLENCE Sin Amoníaco 7U Rubio Caja 1un",
        price: 34,
        description: 'Tinte para cabello permanente con una fórmula rica y duradera.',
        category: Category.HairDye,
        stock: 10,
        quantity: 0,
        imageUrl: '../../assets/image/products/tinte-3.jpg',
        barcode: '9870123456',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Colores vibrantes', 'Fácil de aplicar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: '23',
        name: "Tinte Capilar Permanente EXCELLENCE Sin Amoníaco 2U Marrón Caja 1un",
        price: 34,
        description: 'Tinte para cabello permanente con una fórmula rica y duradera.',
        category: Category.HairDye,
        stock: 10,
        quantity: 0,
        imageUrl: '../../assets/image/products/tinte-4.jpg',
        barcode: '9870123456',
        onSale: false,
        unitsPerPackage: 1,
        reviews: ['Colores vibrantes', 'Fácil de aplicar'],
        created_at: new Date(),
        updated_at: new Date(),
    },
]