import { Reviews } from "../models/reviews";

export const reviewsValue: Reviews[] = [
    {
        _id: 'review1',
        user: 'user2',
        review: 'Servicio excelente, altamente recomendado. ¡Una experiencia maravillosa!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review2',
        user: 'user3',
        review: 'Increíble experiencia facial, dejó mi piel radiante y rejuvenecida.',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review3',
        user: 'user4',
        review: 'Uñas impecables, atención detallada. ¡Me encantó el resultado!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review4',
        user: 'user5',
        review: 'Mejoró la salud de mi cabello notablemente. ¡Un cambio impresionante!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review5',
        user: 'user6',
        review: 'Tratamiento relajante y revitalizante. ¡Una experiencia rejuvenecedora!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review6',
        user: 'user7',
        review: 'Maquillaje impecable, resalta mi belleza natural. ¡Muy satisfecha!',
        qualification: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review7',
        user: 'user8',
        review: 'Peinado elegante, refleja mi estilo. ¡Una obra de arte en cabello!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review8',
        user: 'user9',
        review: 'Paciencia admirable al realizar peinados. ¡Resultado espectacular!',
        qualification: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review9',
        user: 'user10',
        review: 'Puntualidad excepcional. ¡Siempre cumplen con los horarios acordados!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review10',
        user: 'user11',
        review: 'Busca la satisfacción del cliente, atención personalizada. ¡Altamente recomendable!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review11',
        user: 'user12',
        review: 'Productos de calidad, cuidado excepcional para mi cabello. ¡Me encanta!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review12',
        user: 'user13',
        review: 'Precios accesibles, excelente relación calidad-precio. ¡Muy satisfecho!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review13',
        user: 'user14',
        review: 'Cortes variados para todos los gustos, siempre encuentro el estilo perfecto.',
        qualification: 4.5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review14',
        user: 'user15',
        review: 'Aplicación de uñas perfecta, atención detallada. ¡Resultados asombrosos!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'review15',
        user: 'user16',
        review: 'El mejor tratamiento capilar, altamente recomendable. ¡Mi cabello luce increíble!',
        qualification: 5,
        created_at: new Date(),
        updated_at: new Date(),
    },
];
