import { Service } from "../models/service";

export const servicesValue: Service[] = [
    {
        _id: '1',
        name: 'Corte de pelo',
        description: 'Un corte de pelo moderno y elegante',
        price: 50,
        duration: 45,
        category: 'Corte',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Excelente servicio', 'Muy recomendado'],
        tags: ['Corte', 'Estilo', 'Moda'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '2',
        name: 'Tratamientos Faciales',
        description: 'Tratamientos faciales rejuvenecedores',
        price: 50,
        duration: 60,
        category: 'Facial',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Increíble experiencia facial'],
        tags: ['Facial', 'Belleza', 'Relajación'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '3',
        name: 'Manicura y Pedicura',
        description: 'Manicura y pedicura profesional',
        price: 50,
        duration: 60,
        category: 'Manicura',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Uñas perfectas'],
        tags: ['Manicura', 'Pedicura', 'Estilo'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '4',
        name: 'Tratamientos Capilares',
        description: 'Tratamientos capilares para un cabello saludable',
        price: 50,
        duration: 60,
        category: 'Capilar',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Mejoró la salud de mi cabello'],
        tags: ['Capilar', 'Cabello', 'Salud'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '5',
        name: 'Terapias Alternativas',
        description: 'Terapias alternativas para el bienestar general',
        price: 50,
        duration: 60,
        category: 'Bienestar',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Relajante y revitalizante'],
        tags: ['Bienestar', 'Relajación', 'Terapias'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '6',
        name: 'Maquillaje',
        description: 'Maquillaje profesional para eventos especiales',
        price: 50,
        duration: 60,
        category: 'Maquillaje',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Maquillaje impecable'],
        tags: ['Maquillaje', 'Estilo', 'Eventos'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
    {
        _id: '7',
        name: 'Peinados Especiales',
        description: 'Peinados especiales para ocasiones únicas',
        price: 50,
        duration: 60,
        category: 'Peinado',
        availability: true,
        image: '../../../../assets/image/other/corte-cabello.jpg',
        reviews: ['Peinado elegante'],
        tags: ['Peinado', 'Estilo', 'Eventos'],
        discount: 0,
        relatedServices: [],
        created_at: new Date(),
        updated_at: new Date()
    },
];