import { User } from "../models/user";

export const usersValue: User[] = [
    {
        _id: 'user1',
        name: 'Jackelyn',
        last_name: '',
        years_old: 30,
        password: 'admin',
        email: 'admin@gmail.com',
        rol: 'admin',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user2',
        name: 'Pancho',
        last_name: 'Pèrez',
        years_old: 22,
        password: 'pancho',
        email: 'pancho@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user3',
        name: 'Carla',
        last_name: 'Gómez',
        years_old: 31,
        password: 'carla',
        email: 'carla@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user4',
        name: 'Lucia',
        last_name: 'Martínez',
        years_old: 22,
        password: 'lucia',
        email: 'lucia@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user5',
        name: 'Ernesto',
        last_name: 'Malpartida',
        years_old: 38,
        password: 'ernesto',
        email: 'ernesto@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user6',
        name: 'María',
        last_name: 'Santana',
        years_old: 45,
        password: 'maria',
        email: 'maria@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user7',
        name: 'Marta',
        last_name: 'Fernández',
        years_old: 31,
        password: 'marta',
        email: 'marta@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user8',
        name: 'Alejandro',
        last_name: 'Herrera',
        years_old: 22,
        password: 'alejandro',
        email: 'alejandro@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user9',
        name: 'Isabel',
        last_name: 'Ramírez',
        years_old: 38,
        password: 'isabel',
        email: 'isabel@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user10',
        name: 'Carlos',
        last_name: 'Sánchez',
        years_old: 31,
        password: 'carlos',
        email: 'carlos@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user11',
        name: 'Valentina',
        last_name: 'González',
        years_old: 22,
        password: 'valentina',
        email: 'valentina@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user12',
        name: 'Sergio',
        last_name: 'Martínez',
        years_old: 38,
        password: 'sergio',
        email: 'sergio@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user13',
        name: 'Gabriela',
        last_name: 'Mendoza',
        years_old: 45,
        password: 'gabriela',
        email: 'gabriela@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user14',
        name: 'Diego',
        last_name: 'Rodríguez',
        years_old: 31,
        password: 'diego',
        email: 'diego@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user15',
        name: 'Ana',
        last_name: 'López',
        years_old: 22,
        password: 'ana',
        email: 'ana@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
    {
        _id: 'user16',
        name: 'Javier',
        last_name: 'Vargas',
        years_old: 38,
        password: 'javier',
        email: 'javier@gmail.com',
        rol: 'user',
        avatar: '',
        telephone_number: '999999999',

        created_at: new Date(),
        updated_at: new Date(),
    },
]